gfs2/edit: always use "%s"-style format for printf()-style functions
`ncurses-6.3` added printf-style function attributes and now makes
it easier to catch cases when user input is used in place of format
string when built with CFLAGS=-Werror=format-security:

    hexedit.c:227:9: error: format not a string literal and no format arguments [-Werror=format-security]
      227 |         printw(s2);
          |         ^~~~~~

Let's wrap all the missing places with "%s" format.