Include asm/types.h in our linux/types.h
Include asm/types.h to provide __u* and __s*, and __vector128 which
fixes build failures on ppc64le and s390x:

  In file included from /usr/include/asm/sigcontext.h:14,
                   from /usr/include/bits/sigcontext.h:30,
                   from /usr/include/signal.h:291,
                   from hexedit.c:16:
  /usr/include/asm/elf.h:160:9: error: unknown type name ‘__vector128’
   typedef __vector128 elf_vrreg_t;

asm/types.h is included in the original linux/types.h so this reduces
the difference (at the expense of portability).

Signed-off-by: Andrew Price <anprice@redhat.com>