fsck.gfs2: Fix declaration mismatch for invalidate_*
Move the invalidate_fxns struct definition down so that the forward
declarations for those functions can be removed to avoid mismatches.

Fixes sparse error:

  pass1.c:1146:12: error: symbol 'invalidate_data' redeclared with
  different type (incompatible argument 6 (different base types))

Signed-off-by: Andrew Price <anprice@redhat.com>